package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/google/uuid"
	"github.com/satont/stream/apps/api/internal/gql/gqlmodel"
	"github.com/satont/stream/apps/api/internal/repositories/user"
)

// ChatSwitchUserBan is the resolver for the chatSwitchUserBan field.
func (r *mutationResolver) ChatSwitchUserBan(ctx context.Context, input gqlmodel.BanUser) (bool, error) {
	if _, err := r.userRepo.Update(
		ctx,
		uuid.MustParse(input.UserID),
		user.UpdateOpts{IsBanned: &input.NewValue},
	); err != nil {
		return false, err
	}

	return true, nil
}
