package streams

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// thumbnailsHandler proxies preview images generated by OvenMediaEngine,
// so the media server stays hidden behind the API.
func (c *Streams) thumbnailsHandler(ctx *gin.Context) {
	channelName := ctx.Param("channelName")
	dbChannel, err := c.userRepo.FindByName(ctx.Request.Context(), channelName)
	if err != nil {
		c.logger.Sugar().Infow("Channel not found", "err", err, "channel", channelName)
		ctx.Status(http.StatusNotFound)
		return
	}

	thumbnailUrl := fmt.Sprintf(
		"%s/%s/%s/thumb.jpg",
		strings.TrimSuffix(c.config.OmeLlhlsAddr, "/"),
		c.config.OmeApp,
		dbChannel.Name,
	)

	req, err := http.NewRequestWithContext(ctx.Request.Context(), http.MethodGet, thumbnailUrl, nil)
	if err != nil {
		ctx.Status(http.StatusInternalServerError)
		return
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		c.logger.Sugar().Errorw("Failed to fetch thumbnail", "err", err, "url", thumbnailUrl)
		ctx.Status(http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		ctx.Status(http.StatusNotFound)
		return
	}

	ctx.Header("Cache-Control", "public, max-age=5")
	ctx.DataFromReader(http.StatusOK, resp.ContentLength, "image/jpeg", resp.Body, nil)
}

func newThumbnailsHttpClient() *http.Client {
	return &http.Client{
		Timeout: 5 * time.Second,
	}
}
