name: Push mediamtx

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          app: [frontend, api]
    steps:
      - name: Set DOCKER_IMAGE env
        run: |
          echo "DOCKER_IMAGE=$DOCKER_REGISTRY/satont/livestreamx" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to container registry
        uses: docker/login-action@v2
        id: login
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./apps/${{ matrix.app }}//Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ matrix.app }}-latest
            ${{ env.DOCKER_IMAGE }}:${{ matrix.app }}-${{ github.sha }}
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            VITE_STREAM_URL=https://streamx.satont.dev/stream/
          cache-from: type=gha
          cache-to: type=gha,mode=max