name: Build and push mediamtx

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to container registry
        uses: docker/login-action@v2
        id: login
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./mediamtx.Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/satont/livestreamx:mediamtx-latest
            ghcr.io/satont/livestreamx:mediamtx-${{ github.sha }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max